Repository nightsailor/online-school, pull requests merged in 2022-10, with the labels that each got.

#12 fix broken links mentionned in - issue #10
  README.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#14 added pull request template
  .github/pull_request_template.md
Labels: documentation, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#15 new version
  client/src/app/index.js
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#16 View all tests
  .gitignore
  client/package.json
  client/src/app/index.js
  client/src/components/Logo.jsx
  client/src/index.js
  client/src/logo2.png
  client/src/pages/AllTests.jsx
  client/src/pages/TeacherDashboard.jsx
  client/src/pages/index.js
  client/yarn.lock
  server/.env
  server/.gitignore
  server/index.js
  server/yarn.lock
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#18 production ready
  .gitignore
  client/package.json
  client/src/api/index.js
  client/src/app/index.js
  client/src/components/Links.jsx
  client/src/pages/SignIn.jsx
  server/example.env
  server/index.js
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#24 added contributors in README
  README.md
Labels: documentation, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#26 heroku deployment
  package.json
  server/index.js
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#21 docs: CONTRIBUTING: Do not ask to init npm/yarn
  CONTRIBUTING.md
Labels: documentation, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#27 Translated the readme into Romanian
  translate-README/README-ROro.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted
